import NewTodo from "@/components/todos/NewTodo";
import Todos from "@/components/todos/Todos";
import Todo from "@/models/todo";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const todos: Todo[] = [
    {
      id: Math.random(),
      text: "Learn ReactJS",
    },
    {
      id: Math.random(),
      text: "Learn NextJS",
    },
    {
      id: Math.random(),
      text: "Learn Typescript",
    },
  ];

  // !(useState<>()) To set (Type) of (useState) value for (Typescript)
  const [todoList, setTodoList] = useState<Todo[]>(todos);

  const addedTodo = (todoText: string) => {
    // setTodoList((prevState) => [
    //   ...prevState,
    //   { id: Math.random(), text: todo },
    // ]);

    /* const newTodo = { id: Math.random(), text: todo }; */

    const newTodo = new Todo(todoText);
    console.log(newTodo);
    setTodoList((prevState) => {
      return prevState.concat(newTodo);
    });
  };

  const removeTodoHandler = (id: number) => {
    console.log(id);
    setTodoList((prevTodos) => {
      return prevTodos.filter((todo) => todo.id !== id);
    });
  };

  return (
    <>
      <Head>
        <title>React Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 grid grid-cols-1 gap-6">
        <NewTodo onAddTodo={addedTodo} />
        <Todos todos={todoList} onRemoveTodo={removeTodoHandler} />
      </main>
    </>
  );
}
