import MeetupList from "../components/meetups/MeetupList";
import Head from "next/head";
import { Section } from "@/components/ui/igmtink";
import Link from "next/link";

export default function Home() {
  const DUMMY_DB = [
    {
      id: "m1",
      title: "A First Meetup",
      image:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Vue_de_nuit_de_la_Place_Stanislas_%C3%A0_Nancy.jpg/1200px-Vue_de_nuit_de_la_Place_Stanislas_%C3%A0_Nancy.jpg",
      address: "Some address 5, 12345 Some City",
    },
    {
      id: "m2",
      title: "A Second Meetup",
      image:
        "https://www.le-lorrain.fr/files/uploads/2015/07/nancy-770x400.jpg",
      address: "Some address 5, 12345 Some City",
    },
  ];

  return (
    <>
      <Head>
        <title>Meetups</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <Section className="grid grid-cols-1 gap-4">
          <Link
            href="/new-meetup"
            className="text-white bg-neutral-900 rounded-md px-4 py-2 w-fit justify-self-end"
          >
            New
          </Link>
          <MeetupList meetups={DUMMY_DB} />
        </Section>
      </main>
    </>
  );
}
